// <auto-generated />
using System;
using BlazorApp4.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlazorApp4.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp4.Models.ChatDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("BlazorApp4.Models.ChatSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatSnapshots");
                });

            modelBuilder.Entity("BlazorApp4.Models.MessageDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentVersionOrder")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("BlazorApp4.Models.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free"
                        },
                        new
                        {
                            Id = 2,
                            Name = "nvidia/nemotron-3-nano-30b-a3b:free"
                        },
                        new
                        {
                            Id = 3,
                            Name = "nvidia/nemotron-3-super-120b-a12b:free"
                        },
                        new
                        {
                            Id = 4,
                            Name = "poolside/laguna-xs-2.1:free"
                        },
                        new
                        {
                            Id = 5,
                            Name = "cohere/north-mini-code:free"
                        },
                        new
                        {
                            Id = 6,
                            Name = "dots-studio/dots-3-note-preview:free"
                        });
                });

            modelBuilder.Entity("BlazorApp4.Models.SnapshotEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<int>("SnapshotId")
                        .HasColumnType("integer");

                    b.Property<int>("VersionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("VersionId");

                    b.ToTable("SnapshotEntries");
                });

            modelBuilder.Entity("BlazorApp4.Models.VersionDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsOriginal")
                        .HasColumnType("boolean");

                    b.Property<int>("MessageId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("SnapshotId")
                        .HasColumnType("integer");

                    b.Property<int?>("VersionDbId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("SnapshotId");

                    b.HasIndex("VersionDbId");

                    b.ToTable("Versions");
                });

            modelBuilder.Entity("BlazorApp4.Models.ChatSnapshot", b =>
                {
                    b.HasOne("BlazorApp4.Models.ChatDb", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("BlazorApp4.Models.MessageDb", b =>
                {
                    b.HasOne("BlazorApp4.Models.ChatDb", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("BlazorApp4.Models.SnapshotEntry", b =>
                {
                    b.HasOne("BlazorApp4.Models.MessageDb", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp4.Models.ChatSnapshot", "Snapshot")
                        .WithMany("Entries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp4.Models.VersionDb", "Version")
                        .WithMany()
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Snapshot");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("BlazorApp4.Models.VersionDb", b =>
                {
                    b.HasOne("BlazorApp4.Models.MessageDb", "Message")
                        .WithMany("Versions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorApp4.Models.ChatSnapshot", "Snapshot")
                        .WithMany()
                        .HasForeignKey("SnapshotId");

                    b.HasOne("BlazorApp4.Models.VersionDb", null)
                        .WithMany("PreviousVersions")
                        .HasForeignKey("VersionDbId");

                    b.Navigation("Message");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("BlazorApp4.Models.ChatDb", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("BlazorApp4.Models.ChatSnapshot", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("BlazorApp4.Models.MessageDb", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("BlazorApp4.Models.VersionDb", b =>
                {
                    b.Navigation("PreviousVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
